backend:
  # name: test-repo
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "_assets/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: word
    label: Word
    identifier_field: word
    label_singular: "Word"
    folder: words
    path: "{{tags}}/{{word}}"
    create: true
    media_folder: "_assets/img"
    public_folder: "/assets/img"
    # adding a nested object will show the collection folder structure
    fields: # The fields for each document, usually in front matter
      - {
          label: "_layout",
          name: "layout",
          widget: "string",
          default: "word",
          required: false,
        }
      - { label: "Word", name: "word", widget: "string", hint: "e.g. accuracy" }
      - {
          label: "Translation",
          name: "translation",
          widget: "string",
          hint: "مثلا، کارایی",
        }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
          ]

      # - label: "Tags"
      #   name: "tags"
      #   widget: "relation"
      #   collection: "authors"
      #   searchFields: ["name", "github"]
      #   valueField: "name"

      - { label: "Body", name: "body", widget: "markdown" }
    view_filters:
      - label: "A"
        field: tags
        pattern: "A"
      - label: "B"
        field: tags
        pattern: "B"
      - label: "C"
        field: tags
        pattern: "C"
      - label: "D"
        field: tags
        pattern: "D"
      - label: "E"
        field: tags
        pattern: "E"
      - label: "F"
        field: tags
        pattern: "F"
      - label: "G"
        field: tags
        pattern: "G"
      - label: "H"
        field: tags
        pattern: "H"
      - label: "I"
        field: tags
        pattern: "I"
      - label: "J"
        field: tags
        pattern: "J"
      - label: "K"
        field: tags
        pattern: "K"
      - label: "L"
        field: tags
        pattern: "L"
      - label: "M"
        field: tags
        pattern: "M"
      - label: "N"
        field: tags
        pattern: "N"
      - label: "O"
        field: tags
        pattern: "O"
      - label: "P"
        field: tags
        pattern: "P"
      - label: "Q"
        field: tags
        pattern: "Q"
      - label: "R"
        field: tags
        pattern: "R"
      - label: "S"
        field: tags
        pattern: "S"
      - label: "T"
        field: tags
        pattern: "T"
      - label: "U"
        field: tags
        pattern: "U"
      - label: "V"
        field: tags
        pattern: "V"
      - label: "W"
        field: tags
        pattern: "W"
      - label: "X"
        field: tags
        pattern: "X"
      - label: "Y"
        field: tags
        pattern: "Y"
      - label: "Z"
        field: tags
        pattern: "Z"
